### ISSUE TITLE
Problems with the callback

### ISSUE THREAD

**Issue by SantiFerre** [YoYoGames/GMEXT-MobileReview#1]
I have a problem with the extension. When I call it once, in the subsequent attempts, Google blocks the in-app review. My issue is that when I want to check if the popup doesn't open, the callback variable 'success' always returns 1.0. I want that when the popup doesn't open, the browser launches with the game page.

Thank you in advance

**Comment by jzavala-YYG** [comment]
**_success_** key return true if operation was requested successful, Popup will appear only the first request, my recommendation it's save locally if review was requested and **_success_** returned true and don't request more times after that first time
