### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by KBeeeR** [YoYoGames/GMEXT-MobileReview#4]
Google play shows this warning
Warning
The developer of Google Play Core (com.google.android.play:core) added the following note to SDK version 1.8.0:
If your app is targeting SDK 34+ (targetSdkVersion), then the PlayCore SDK is outdated and will likely cause crashes in your app! Please update: https://developer.android.com/guide/playcore#playcore-migration

**Comment by jzavala-YYG** [comment]
Hello @KBeeeR

Updated one week ago, you can downloaded directly from this repository or wait the update on marketplace.

Regards
